controller_manager:
  ros__parameters:
    update_rate: 50 # Hz

    tricycle_controller:
      type: tricycle_controller/TricycleController
      

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_state_broadcaster:
  ros__parameters:
    extra_joints: ["fork_right_wheel_joint", "fork_left_wheel_joint"]

tricycle_controller:
  ros__parameters:
    # Model
    traction_joint_name: front_wheel_joint # Name of traction joint in URDF
    steering_joint_name: steering_cylinder_joint # Name of steering joint in URDF
    wheel_radius: 0.07 # Radius of front wheel
    wheelbase: 1.015 # Distance between center of back wheels and front wheel

    # Odometry
    odom_frame_id: odom
    base_frame_id: base_link
    publish_rate: 50.0 # publish rate of odom and tf
    open_loop: false # if True, uses cmd_vel instead of hardware interface feedback to compute odometry
    enable_odom_tf: false # If True, publishes odom<-base_link TF
    odom_only_twist: false # If True, publishes on /odom only linear.x and angular.z; Useful for computing odometry in another node, e.g robot_localization's ekf
    pose_covariance_diagonal: [0.01, 0.01, 9999.0, 9999.0, 9999.0, 0.01] # Need to be set if fusing odom with other localization source
    twist_covariance_diagonal: [0.01, 0.01, 9999.0, 9999.0, 9999.0, 0.01] # Need to be set if fusing odom with other localization source
    velocity_rolling_window_size: 10 # Rolling window size of rcppmath::RollingMeanAccumulator applied on linear and angular speeds published on odom
    # Rate Limiting
    traction: # All values should be positive
      # min_velocity: 0.0
      # max_velocity: 1000.0
      # min_acceleration: 0.0
      max_acceleration: 5.0
      # min_deceleration: 0.0
      max_deceleration: 8.0
      # min_jerk: 0.0
      # max_jerk: 1000.0
    steering:
      min_position: -70.0
      max_position: 70.0
      # min_velocity: 0.0
      max_velocity: 10.0
      # min_acceleration: 0.0
      # max_acceleration: 1000.0

    # cmd_vel input
    topic: /tricycle_controller/cmd_vel
    cmd_vel_timeout: 500 # In milliseconds. Timeout to stop if no cmd_vel is received
    use_stamped_vel: false # Set to True if using TwistStamped.


    front_wheel_command_interface: velocity
    front_wheel_state_interface: [velocity, position]
    steer_command_interface: position
    steer_state_interface: [velocity, position]
    